In [37]:
import numpy as np
import pandas as pd

In [38]:
True_news = pd.read_csv('True.csv')
Fake_news = pd.read_csv('Fake.csv')

In [39]:
True_news['label'] = 0
Fake_news['label'] = 1

In [40]:
dataset1 = True_news[['text', 'label']]
dataset2 = Fake_news[['text', 'label']]

In [41]:
combined_df=pd.concat([dataset1 ,dataset2])

In [42]:
combined_df

text  label
0    WASHINGTON (Reuters) - The head of a conservat...      0
1    WASHINGTON (Reuters) - Transgender people will...      0
2    WASHINGTON (Reuters) - The special counsel inv...      0
3    WASHINGTON (Reuters) - Trump campaign adviser ...      0
4    SEATTLE/WASHINGTON (Reuters) - President Donal...      0
..                                                 ...    ...
995  Not long ago, Rep. Jason Chaffetz (R-Utah), sa...      1
996  According to a new report, health insurance pr...      1
997  The Congressional Budget Office released their...      1
998  Donald Trump was in a room full of Irish repor...      1
999  Donald Trump s war on the free press just ente...      1

[2000 rows x 2 columns]

In [43]:
combined_df.shape

(2000, 2)

In [44]:
combined_df.isnull().sum()

text     0
label    0
dtype: int64

In [45]:
from scipy import stats

label_mean = combined_df['label'].mean()
label_median = combined_df['label'].median()
label_mode_result = stats.mode(combined_df['label'])

# Access mode and its count directly without indexing
label_mode = label_mode_result.mode
label_mode_count = label_mode_result.count

print(f"Mean: {label_mean}")
print(f"Median: {label_median}")
print(f"Mode: {label_mode} (occurs {label_mode_count} times)")


Mean: 0.5
Median: 0.5
Mode: 0 (occurs 1000 times)


In [46]:
# Perform ANOVA F-test
f_statistic, p_value = stats.f_oneway(combined_df[combined_df['label'] == 0]['label'],
 combined_df[combined_df['label'] == 1]['label'])
print(f"F-statistic: {f_statistic}")
print(f"P-value: {p_value}")

F-statistic: inf
P-value: 0.0


C:\Users\Hp\AppData\Local\Temp\ipykernel_10604\3220037983.py:2: ConstantInputWarning: Each of the input arrays is constant; the F statistic is not defined or infinite
  f_statistic, p_value = stats.f_oneway(combined_df[combined_df['label'] == 0]['label'],


In [47]:
# Create a new column 'text_length' with the length of the 'text' column
combined_df['text_length'] = combined_df['text'].apply(lambda x: len(x.split()))
# Separate text lengths for the two groups
true_text_length = combined_df[combined_df['label'] == 0]['text_length']
fake_text_length = combined_df[combined_df['label'] == 1]['text_length']


In [48]:
# Perform an independent t-test
t_statistic, p_value = stats.ttest_ind(true_text_length, fake_text_length)
print(f"T-statistic: {t_statistic}")
print(f"P-value: {p_value}")

T-statistic: -2.5639058981394967
P-value: 0.01042271414679376


In [49]:
from scipy.stats import chi2_contingency
# Replace "Your_Categorical_Variable" with the actual categorical variable name
categorical_variable ='label'
# Create a contingency table to assess the association between 'label' and the categorical variable
contingency_table = pd.crosstab(combined_df['label'], combined_df[categorical_variable])
# Perform a chi-squared test
chi2, p, _, _ = chi2_contingency(contingency_table)
print(f"Chi-squared statistic: {chi2}")
print(f"P-value: {p}")


Chi-squared statistic: 1996.002
P-value: 0.0


In [50]:
import statsmodels.api as sm
# Specify the independent variable (label) and dependent variable (word count)
X = combined_df[['label']] # Independent variable
y = combined_df['text_length'] # Dependent variable
# Add a constant term to the independent variable (intercept)
X = sm.add_constant(X)
# Fit a linear regression model
model = sm.OLS(y, X).fit()
# Get the regression summary
print(model.summary())


                            OLS Regression Results                            
Dep. Variable:            text_length   R-squared:                       0.003
Model:                            OLS   Adj. R-squared:                  0.003
Method:                 Least Squares   F-statistic:                     6.574
Date:                Wed, 07 Feb 2024   Prob (F-statistic):             0.0104
Time:                        00:14:40   Log-Likelihood:                -13564.
No. Observations:                2000   AIC:                         2.713e+04
Df Residuals:                    1998   BIC:                         2.714e+04
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        393.4860      6.751     58.282      0.0

In [52]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
# Specify the independent variables (features) and the target variable (label)
X = combined_df[['text_length']] # Replace with your feature columns
y = combined_df['label'] # Target variable
# Split the data into a training set and a testing set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, 
random_state=42)
# Initialize and fit the logistic regression model
logistic_regression = LogisticRegression()
logistic_regression.fit(X_train, y_train)
# Make predictions on the testing set
y_pred = logistic_regression.predict(X_test)
# Evaluate the model's performance
accuracy = accuracy_score(y_test, y_pred)
confusion = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)
print(f"Accuracy: {accuracy}")
print(f"Confusion Matrix:\n{confusion}")
print(f"Classification Report:\n{classification_rep}")

Accuracy: 0.52
Confusion Matrix:
[[125  74]
 [118  83]]
Classification Report:
              precision    recall  f1-score   support

           0       0.51      0.63      0.57       199
           1       0.53      0.41      0.46       201

    accuracy                           0.52       400
   macro avg       0.52      0.52      0.51       400
weighted avg       0.52      0.52      0.51       400



In [53]:
from sklearn.tree import DecisionTreeClassifier, plot_tree
# Initialize and fit the decision tree classifier
decision_tree = DecisionTreeClassifier()
decision_tree.fit(X_train, y_train)
# Make predictions on the testing set
y_pred = decision_tree.predict(X_test)
# Evaluate the model's performance
accuracy = accuracy_score(y_test, y_pred)
confusion = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)
print(f"Accuracy: {accuracy}")
print(f"Confusion Matrix:\n{confusion}")
print(f"Classification Report:\n{classification_rep}")

Accuracy: 0.6825
Confusion Matrix:
[[132  67]
 [ 60 141]]
Classification Report:
              precision    recall  f1-score   support

           0       0.69      0.66      0.68       199
           1       0.68      0.70      0.69       201

    accuracy                           0.68       400
   macro avg       0.68      0.68      0.68       400
weighted avg       0.68      0.68      0.68       400



In [54]:
from sklearn.ensemble import RandomForestClassifier
# Initialize and fit the Random Forest classifier
random_forest = RandomForestClassifier(n_estimators=100, random_state=42)
random_forest.fit(X_train, y_train)
# Make predictions on the testing set
y_pred = random_forest.predict(X_test)
# Evaluate the model's performance
accuracy = accuracy_score(y_test, y_pred)
confusion = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)
print(f"Accuracy: {accuracy}")
print(f"Confusion Matrix:\n{confusion}")
print(f"Classification Report:\n{classification_rep}")

Accuracy: 0.7025
Confusion Matrix:
[[128  71]
 [ 48 153]]
Classification Report:
              precision    recall  f1-score   support

           0       0.73      0.64      0.68       199
           1       0.68      0.76      0.72       201

    accuracy                           0.70       400
   macro avg       0.71      0.70      0.70       400
weighted avg       0.71      0.70      0.70       400



In [55]:
from sklearn.neighbors import KNeighborsClassifier
# Initialize and fit the K-NN classifier
knn = KNeighborsClassifier(n_neighbors=5) # You can adjust the number of neighbors (k) as needed
knn.fit(X_train, y_train)
# Make predictions on the testing set
y_pred = knn.predict(X_test)
# Evaluate the model's performance
accuracy = accuracy_score(y_test, y_pred)
confusion = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)
print(f"Accuracy: {accuracy}")
print(f"Confusion Matrix:\n{confusion}")
print(f"Classification Report:\n{classification_rep}")

Accuracy: 0.6975
Confusion Matrix:
[[123  76]
 [ 45 156]]
Classification Report:
              precision    recall  f1-score   support

           0       0.73      0.62      0.67       199
           1       0.67      0.78      0.72       201

    accuracy                           0.70       400
   macro avg       0.70      0.70      0.70       400
weighted avg       0.70      0.70      0.70       400



In [56]:
from sklearn.svm import SVC
# Initialize and fit the SVM classifier
svm_classifier = SVC(kernel='linear') # You can choose different kernels such as 'linear', 'rbf', or 'poly'
svm_classifier.fit(X_train, y_train)
# Make predictions on the testing set
y_pred = svm_classifier.predict(X_test)
# Evaluate the model's performance
accuracy = accuracy_score(y_test, y_pred)
confusion = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)
print(f"Accuracy: {accuracy}")
print(f"Confusion Matrix:\n{confusion}")
print(f"Classification Report:\n{classification_rep}")

Accuracy: 0.555
Confusion Matrix:
[[100  99]
 [ 79 122]]
Classification Report:
              precision    recall  f1-score   support

           0       0.56      0.50      0.53       199
           1       0.55      0.61      0.58       201

    accuracy                           0.56       400
   macro avg       0.56      0.55      0.55       400
weighted avg       0.56      0.56      0.55       400



In [ ]:
import keras
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
# Build the ANN model
max_words=10000
max_sequence_length=10000
model = keras.Sequential([
 keras.layers.Embedding(input_dim=max_words, output_dim=16, 
input_length=max_sequence_length),
 keras.layers.Flatten(),
 keras.layers.Dense(64, activation='relu'),
 keras.layers.Dense(1, activation='sigmoid')
])
# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.1, 
random_state=42)
# Train the model
model.fit(X_train, y_train, epochs=5, batch_size=64, validation_data=(X_val, 
y_val))
# Evaluate the model on the test set
test_loss, test_accuracy = model.evaluate(X_test, y_test)
print(f"Test accuracy: {test_accuracy}")


In [57]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans

# Now you can use TfidfVectorizer in your code
combined_text = pd.concat([dataset1['text'], dataset2['text']])
# Preprocess the text data using TF-IDF vectorization
tfidf_vectorizer = TfidfVectorizer(max_features=1000) # Adjust the number of features as needed
tfidf_matrix = tfidf_vectorizer.fit_transform(combined_text)
# Perform K-Means clustering
num_clusters = 2 # Assuming you want to separate true news and fake news
kmeans = KMeans(n_clusters=num_clusters)
kmeans.fit(tfidf_matrix)
# Add cluster labels to your DataFrames
dataset1['cluster_label'] = kmeans.labels_[:len(dataset1)]
dataset2['cluster_label'] = kmeans.labels_[len(dataset1):]
# Print cluster centers (optional)
print("Cluster Centers:")
print(kmeans.cluster_centers_)


Cluster Centers:
[[0.01044457 0.00928839 0.0038981  ... 0.00573443 0.00301271 0.00202795]
 [0.00780698 0.00650123 0.00226734 ... 0.05743144 0.00507113 0.01622004]]


C:\Users\Hp\AppData\Local\Temp\ipykernel_10604\548355031.py:14: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset1['cluster_label'] = kmeans.labels_[:len(dataset1)]
C:\Users\Hp\AppData\Local\Temp\ipykernel_10604\548355031.py:15: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset2['cluster_label'] = kmeans.labels_[len(dataset1):]


In [58]:
from sklearn.decomposition import PCA
from sklearn.decomposition import TruncatedSVD
# Preprocess the text data using TF-IDF vectorization
tfidf_vectorizer = TfidfVectorizer(max_features=1000) # Adjust the number of features as needed
tfidf_matrix = tfidf_vectorizer.fit_transform(combined_text)
# Perform Truncated SVD (PCA alternative) to reduce dimensionality
n_components = 50 # Number of components to retain
svd = TruncatedSVD(n_components=n_components)
tfidf_svd = svd.fit_transform(tfidf_matrix)
# Perform K-Means clustering on the SVD-transformed data
num_clusters = 2 # Assuming you want to separate true news and fake news
kmeans = KMeans(n_clusters=num_clusters)
kmeans.fit(tfidf_svd)
# Add cluster labels to your DataFrames
dataset1['cluster_label'] = kmeans.labels_[:len(dataset1)]
dataset2['cluster_label'] = kmeans.labels_[len(dataset1):]
# Print cluster centers (optional)
print("Cluster Centers:")
print(kmeans.cluster_centers_)


Cluster Centers:
[[ 5.40786658e-01 -4.66265749e-02  1.92879814e-02  5.87697882e-03
  -5.93529014e-03  4.47971295e-03 -1.70942379e-03  1.82507954e-03
   3.31031633e-03  2.88937123e-04 -3.62122127e-03  2.13036602e-03
   4.02710134e-03  1.36590531e-03 -4.45038919e-04  8.69028429e-04
   4.04312643e-04  2.12191232e-03 -3.58221964e-03  1.41873618e-04
  -9.49558385e-04  1.47329063e-03  6.85916970e-04  2.67735491e-04
   1.38750169e-03  2.60001282e-04  1.81911812e-03  6.23482691e-04
   1.33402930e-03  2.20163436e-04 -9.73120878e-04  1.08978424e-03
  -1.25261034e-03  7.52321983e-04 -1.70934130e-04  9.83689809e-04
   6.68561585e-04  7.41210473e-04 -4.43880152e-04  4.83736231e-04
  -8.09727328e-04  4.90164860e-04  1.16691965e-05  1.43432266e-04
   5.73090239e-04  4.65113034e-04 -6.48067550e-04  1.02228687e-05
   1.10576281e-03  4.30038112e-05]
 [ 4.87026122e-01  3.50231861e-01 -1.06323219e-01 -1.91418787e-02
   7.80511227e-02  1.63582539e-02  1.26394723e-03 -6.95842455e-03
   8.69663312e-03  3.264

C:\Users\Hp\AppData\Local\Temp\ipykernel_10604\2025213584.py:15: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset1['cluster_label'] = kmeans.labels_[:len(dataset1)]
C:\Users\Hp\AppData\Local\Temp\ipykernel_10604\2025213584.py:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset2['cluster_label'] = kmeans.labels_[len(dataset1):]


In [59]:
from sklearn.metrics import silhouette_score
silhouette_avg = silhouette_score(tfidf_svd, kmeans.labels_)
print(f"Silhouette Score: {silhouette_avg}")

Silhouette Score: 0.1288050372823802


In [60]:
inertia = kmeans.inertia_
print(f"Inertia: {inertia}")

Inertia: 491.1639596644791


In [61]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
# Create true labels based on your domain knowledge
true_labels = [0] * len(dataset1) + [1] * len(dataset2)
accuracy = accuracy_score(true_labels, kmeans.labels_)
confusion = confusion_matrix(true_labels, kmeans.labels_)
report = classification_report(true_labels, kmeans.labels_)
print(f"Accuracy: {accuracy}")
print("Confusion Matrix:\n", confusion)
print("Classification Report:\n", report)

Accuracy: 0.3765
Confusion Matrix:
 [[746 254]
 [993   7]]
Classification Report:
               precision    recall  f1-score   support

           0       0.43      0.75      0.54      1000
           1       0.03      0.01      0.01      1000

    accuracy                           0.38      2000
   macro avg       0.23      0.38      0.28      2000
weighted avg       0.23      0.38      0.28      2000

